// Regenerate src/styles/fonts.css from the @fontsource packages: node scripts/fonts.mjs
// Same fonts, weights and unicode-range slices as the Google Fonts link it replaces, woff2 only.
import { readFileSync, writeFileSync } from 'node:fs';

const root = new URL('..', import.meta.url).pathname;
const faces = [
  ['geist', [400, 500, 600]],
  ['geist-mono', [400, 500]],
  ['noto-sans-tc', [400, 500, 700]],
];
let css = '/* Generated by scripts/fonts.mjs, do not edit */\n';
for (const [pkg, weights] of faces) {
  for (const w of weights) {
    const src = readFileSync(`${root}node_modules/@fontsource/${pkg}/${w}.css`, 'utf8');
    css += src
      .replace(/, url\([^)]*\.woff\) format\('woff'\)/g, '')
      .replace(/url\(\.\/files\//g, `url(../../node_modules/@fontsource/${pkg}/files/`);
  }
}
writeFileSync(`${root}src/styles/fonts.css`, css);
console.log('fonts.css', css.length, 'bytes');
