import type { Lang, Project } from './projects';
import { projects } from './projects';
import { site, tx, shortTitle } from './site';

/** Absolute origin plus base path, e.g. https://agilenpi.com/portfolio */
export const SITE_URL = `${import.meta.env.SITE.replace(/\/$/, '')}${import.meta.env.BASE_URL.replace(/\/$/, '')}`;

/** Absolute URL of a page; path is the part after base and language, e.g. '/' or '/yoution/' */
export const pageUrl = (lang: Lang, path: string) => `${SITE_URL}${lang === 'en' ? '/en' : ''}${path}`;

/** Social share image for a page, generated by scripts/og.mjs into public/og/ */
export const ogImage = (lang: Lang, slug = 'home') => `${SITE_URL}/og/${slug}-${lang}.jpg`;

const PERSON_ID = `${SITE_URL}/#person`;

/** '2026.07 – 2026.09' → '2026-07' */
const firstMonth = (period: string) => period.match(/(\d{4})\.(\d{2})/)?.slice(1).join('-');

export function personLd(lang: Lang) {
  return {
    '@type': 'Person',
    '@id': PERSON_ID,
    name: 'Sam Lu',
    alternateName: ['呂兆中', '呂兆中 Sam'],
    jobTitle: tx(lang, site.role),
    description: tx(lang, site.intro),
    url: pageUrl(lang, '/'),
    image: ogImage(lang),
    email: `mailto:${site.links.email}`,
    sameAs: [site.links.github, site.links.linkedin],
    knowsAbout: site.skills.flatMap((g) => g.items),
    worksFor: { '@type': 'Organization', name: 'AgileNPI LLC', url: 'https://agilenpi.com/' },
    alumniOf: [
      { '@type': 'CollegeOrUniversity', name: 'Brunel University' },
      { '@type': 'CollegeOrUniversity', name: 'National Chi Nan University' },
    ],
  };
}

export function homeLd(lang: Lang) {
  const url = pageUrl(lang, '/');
  return {
    '@context': 'https://schema.org',
    '@graph': [
      personLd(lang),
      { '@type': 'WebSite', '@id': `${SITE_URL}/#website`, url: pageUrl('zh', '/'), name: 'Sam Lu Portfolio', inLanguage: ['zh-Hant-TW', 'en'], publisher: { '@id': PERSON_ID } },
      {
        '@type': 'ProfilePage',
        url,
        name: `${tx(lang, site.name)} · ${tx(lang, site.role)}`,
        inLanguage: lang === 'zh' ? 'zh-Hant-TW' : 'en',
        mainEntity: { '@id': PERSON_ID },
        hasPart: projects.map((p) => ({ '@type': 'WebPage', url: pageUrl(lang, `/${p.slug}/`), name: shortTitle(lang, p.title) })),
      },
    ],
  };
}

/** Schema type per project: shipped apps are applications, the rest are source code with a public repo */
function workLd(lang: Lang, p: Project) {
  const github = p.home.links?.find((l) => l.kind === 'github')?.href;
  const stores = (p.home.links ?? []).filter((l) => l.kind === 'ios' || l.kind === 'android' || l.kind === 'chrome').map((l) => (typeof l.href === 'string' ? l.href : tx(lang, l.href)));
  const web = p.home.links?.find((l) => l.kind === 'web')?.href;
  const base = {
    name: shortTitle(lang, p.title),
    description: tx(lang, p.tagline),
    url: pageUrl(lang, `/${p.slug}/`),
    image: ogImage(lang, p.slug),
    dateCreated: firstMonth(p.period),
    inLanguage: lang === 'zh' ? 'zh-Hant-TW' : 'en',
    author: { '@id': PERSON_ID },
    keywords: p.home.tags.join(', '),
  };
  if (p.slug === 'yoution') {
    return { '@type': 'SoftwareApplication', ...base, applicationCategory: 'EducationalApplication', operatingSystem: 'Web, iOS, Android, Chrome', sameAs: ['https://yoution.app', ...stores] };
  }
  if (p.slug === 'focus-correction') {
    return { '@type': 'MobileApplication', ...base, applicationCategory: 'ProductivityApplication', operatingSystem: 'iOS, Android', sameAs: stores };
  }
  return {
    '@type': 'SoftwareSourceCode',
    ...base,
    ...(github && { codeRepository: typeof github === 'string' ? github : tx(lang, github) }),
    ...(web && { sameAs: typeof web === 'string' ? web : tx(lang, web) }),
    programmingLanguage: p.stack.filter((s) => /^(Python|TypeScript|Node\.js|JavaScript)/.test(s)),
  };
}

export function projectLd(lang: Lang, p: Project) {
  return {
    '@context': 'https://schema.org',
    '@graph': [
      personLd(lang),
      workLd(lang, p),
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Portfolio', item: pageUrl(lang, '/') },
          { '@type': 'ListItem', position: 2, name: shortTitle(lang, p.title), item: pageUrl(lang, `/${p.slug}/`) },
        ],
      },
    ],
  };
}
